version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: meydey
      MONGO_INITDB_ROOT_PASSWORD: meydeymeydey
    volumes:
      - mongodb-data:/data/db

  app:
    build: .
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://meydey:meydeymeydey@mongodb/geoServices
    ports:
        - "80:8080"
    depends_on:
      - mongodb


volumes:
  mongodb-data:
